### ISSUE TITLE
Discord Appearance Resets

### ISSUE THREAD

**Issue by ghost** [j-f1/discord-plugins#1]
When PC is put to sleep, the theme resets from dark mode to light mode.

**Comment by j-f1** [comment]
I’ve seen this too but I’m not sure why it happens. Going to let my laptop sleep for a bit to see if my additional logging turns anything up.

**Comment by j-f1** [comment]
ok looks like Discord is resetting it somehow. Will try calling the theme change function more often.

**Comment by j-f1** [comment]
I pushed an update but will continue to monitor this! Let me know if you see it happening again on v1.1.3.
