### ISSUE TITLE
SubtleDevicePrompt Dialog Box isnt appearing instead the normal discord prompt box shows.

### ISSUE THREAD

**Issue by IamNickerson** [j-f1/discord-plugins#2]
Hey,
The SubtleDevicePrompt Dialog Box isn't appearing instead the normal discord prompt Box is showing instead of it.

**Comment by j-f1** [comment]
Hello! I've experienced this too. It looks like in addition to some easier-to-adapt-to changes in how things are styled, Discord has significantly updated how they display the connected device modal. That means I'll have to hook into the code differently to both stop the modal from displaying and present its content in the sidebar. As a result, it may take a while to get the fix out.

**Comment by IamNickerson** [comment]
Okay

**Comment by IamNickerson** [comment]
Hey just a gentle reminder Zerenpluginlib got an update.

**Comment by IamNickerson** [comment]
check docs: https://rauenzi.github.io/BDPluginLibrary/docs

**Comment by j-f1** [comment]
Hi @IamNickerson, I’ve updated the plugin to work with the changes to Discord and pushed the new version here. Currently, the version on betterdiscord.app and available through the plugin repo is not up to date but hopefully that will be fixed soon.

**Comment by j-f1** [comment]
…and the update has been approved for the plugin repo so SubtleDevicePrompt should be working for you shortly!

**Comment by IamNickerson** [comment]
> Hi @IamNickerson, I’ve updated the plugin to work with the changes to Discord and pushed the new version here. Currently, the version on betterdiscord.app and available through the plugin repo is not up to date but hopefully that will be fixed soon.

Okay

**Comment by IamNickerson** [comment]
> …and the update has been approved for the plugin repo so SubtleDevicePrompt should be working for you shortly!

Cool

**Comment by IamNickerson** [comment]
Just waiting for the update to come in discord client

**Comment by IamNickerson** [comment]
Ok got the update

**Comment by IamNickerson** [comment]
Ok fixed.

**Comment by j-f1** [comment]
Awesome!
