### ISSUE TITLE
Crashes Discord on Sharing Screen

### ISSUE THREAD

**Issue by nirgranth** [j-f1/discord-plugins#3]
Any stream will instanty freeze discord

**Comment by j-f1** [comment]
Which plugin are you using? And have you confirmed the freeze doesn’t occur if you have all of my plugins disabled?

**Comment by nirgranth** [comment]
its just on subtle device prompt, yes i tested it multiple time its just that plugin, it work fine with out it

**Comment by j-f1** [comment]
I joined a voice channel with only me in it, started sharing a screen, and tried several things (including stopping screen sharing, changing what’s being shared, opening the voice channel, and switching to a different server so the picture-in-picture screen shows up). Nothing caused a freeze for me (Canary 123610 (28a76e9), BetterDiscord 1.5.3, Host 0.0.283, macOS 12.3.1 (21E258)). I unfortunately don’t have access to a non-Mac at this point so I won’t be able to test with other OSes. If you’re able to collect a recording of the issue occurring (using the “Performance” tab of the devtools, click the “Record” button at the top left, then reproduce the issue, then hit the stop button and then “save profile,” then upload here), I might be able to identify and fix the issue. No promises, though, sorry :(

**Comment by nirgranth** [comment]
i tried doing this but the entire process crashes i cant seem to stop the recording
i can provide a obs recording if you would like

**Comment by nirgranth** [comment]
the performance recording works fine until i try to reproduce the issue
![image](https://user-images.githubusercontent.com/48947296/163441589-1ac050f7-9f5d-45b2-94b9-c59483b8f8dc.png)
this is the error it give me if i try to stop the recording after crashing discord

**Comment by j-f1** [comment]
hm, ok. That looks like an error with the service worker (if Discord uses one). That shouldn’t be a big deal, it just means the devtools will provide slightly less useful information. Unfortunately, if I can’t reproduce the issue on my end I won’t be able to fix it. And looking through my plugin code I don’t really see anything that could cause a freeze.

I think at this point, your best option is to disable my plugin. Sorry about that!
