### ISSUE TITLE
SubtleDevicePrompt doesn't seem to work on the recent Discord update

### ISSUE THREAD

**Issue by TheChilliPL** [j-f1/discord-plugins#4]
Doesn't throw any errors, but the device prompt shown is the default one.

**Comment by j-f1** [comment]
Hi! I tested on both Canary and stable versions of Discord (on macOS) and was unable to reproduce this issue. Are you still experiencing this, and if so, what operating system are you on? Also, can you send me (copy+paste) any errors you’re seeing in the browser console? That way I stand a better chance of figuring out what’s going on.

**Comment by TheChilliPL** [comment]
It's weird, now it doesn't seem to show any “new device” prompts whatsoever, and I cannot find the local storage entry to make that work again 🤔
(It could also be a great idea to add a “turn device prompts back on” in the plugin settings, to make it easier to do)

**Comment by j-f1** [comment]
I’m not entirely sure how that part works either — at least on Mac I suspect it’s done natively somewhat. When building the plugin, I had luck with restarting Discord and/or my computer to get the prompt to show up again.

**Comment by TheChilliPL** [comment]
SubtleDevicePrompt is on:
![image](https://user-images.githubusercontent.com/18823939/166436508-7f4b2707-0651-4782-91d6-73d2ac62604e.png)
Yet the shown device prompt is the default one:
![image](https://user-images.githubusercontent.com/18823939/166436407-17b1a921-36ff-418e-baf8-3c56f10d6d0f.png)

**Comment by j-f1** [comment]
Oh, I see the issue! You have v1.0.0 installed, while the latest version is v1.1.1. Discord changed the way they open that dialog back in January, and I had to make an update. I recommend using BetterDiscord’s plugin repo because it handles updates for you.
