### ISSUE TITLE
new discord update broke most plugins

### ISSUE THREAD

**Issue by Squishyzbear** [j-f1/discord-plugins#7]
will you be updating this for the new update?

**Comment by j-f1** [comment]
Yes, I plan to update SubtleDevicePrompt at some point. Currently, I’m waiting for the BD developers to restore some of BD’s patching capabilities before I try to rewrite the plugin.

**Comment by angsaysroar** [comment]
Hello, I was wondering if there any new information about the update for Subtle Device Prompt?

**Comment by j-f1** [comment]
Hi, I can no longer maintain SubtleDevicePrompt.I would love it if someone were to fork it and republish, though!
